//
// Generated by ip_gen_sv_wrapper.tcl
//

module reset_release_sv
  import reset_release_param_pkg::*;
(
  output wire ninit_done
);

  reset_release reset_release (
    .ninit_done(ninit_done)
  );


endmodule
