//
// Generated by ip_gen_sv_wrapper.tcl
//

`ifndef __RESET_RELEASE_IP_PARAMS_H__
`define __RESET_RELEASE_IP_PARAMS_H__


//
// s10_user_rst_clkgate_0 other IP configuration parameters affecting generation
//

`define S10_USER_RST_CLKGATE_0_PARAM_OUTPUTTYPE    "Reset Interface"

`endif  // __RESET_RELEASE_IP_PARAMS_H__
