//
// Generated by ip_gen_sv_wrapper.tcl
//

`ifndef __RESET_RELEASE_IF_INFO_H__
`define __RESET_RELEASE_IF_INFO_H__

//
// Macros describing SystemVerilog interfaces. Interface macros indicate
// both the presence of a signal and its width.
//


//
// Macros describing reset_release_sv module ports
//

`define RESET_RELEASE_HAS_PORT_NINIT_DONE 1
`define RESET_RELEASE_PORT_WIDTH_NINIT_DONE 1


`endif  // __RESET_RELEASE_IF_INFO_H__
